// GET USERDATA 
export const REQ_FOR_GET_USERDATA_PROGRESS = "REQ_FOR_GET_USERDATA_PROGRESS"
export const REQ_FOR_GET_USERDATA_SUCCESS = "REQ_FOR_GET_USERDATA_SUCCESS"
export const REQ_FOR_GET_USERDATA_ERROR = "REQ_FOR_GET_USERDATA_ERROR"

// =============================== CHANGE PASSWORD =======================================
// PATCH 
export const REQ_FOR_PATCH_CHANGEPASSWORD_ADMIN_PROGRESS = "REQ_FOR_PATCH_CHANGEPASSWORD_ADMIN_PROGRESS"
export const REQ_FOR_PATCH_CHANGEPASSWORD_ADMIN_SUCCESS = "REQ_FOR_PATCH_CHANGEPASSWORD_ADMIN_SUCCESS"
export const REQ_FOR_PATCH_CHANGEPASSWORD_ADMIN_ERROR = "REQ_FOR_PATCH_CHANGEPASSWORD_ADMIN_ERROR"

// =============================== LOCATION DATA =======================================

// GET 
export const REQ_FOR_GET_LOCATION_DATA_ADMIN_PROGRESS = "REQ_FOR_GET_LOCATION_DATA_ADMIN_PROGRESS"
export const REQ_FOR_GET_LOCATION_DATA_ADMIN_SUCCESS = "REQ_FOR_GET_LOCATION_DATA_ADMIN_SUCCESS"
export const REQ_FOR_GET_LOCATION_DATA_ADMIN_ERROR = "REQ_FOR_GET_LOCATION_DATA_ADMIN_ERROR"
// POST 
export const REQ_FOR_POST_LOCATION_DATA_ADMIN_PROGRESS = "REQ_FOR_POST_LOCATION_DATA_ADMIN_PROGRESS"
export const REQ_FOR_POST_LOCATION_DATA_ADMIN_SUCCESS = "REQ_FOR_POST_LOCATION_DATA_ADMIN_SUCCESS"
export const REQ_FOR_POST_LOCATION_DATA_ADMIN_ERROR = "REQ_FOR_POST_LOCATION_DATA_ADMIN_ERROR"
// PATCH 
export const REQ_FOR_PATCH_LOCATION_DATA_ADMIN_PROGRESS = "REQ_FOR_PATCH_LOCATION_DATA_ADMIN_PROGRESS"
export const REQ_FOR_PATCH_LOCATION_DATA_ADMIN_SUCCESS = "REQ_FOR_PATCH_LOCATION_DATA_ADMIN_SUCCESS"
export const REQ_FOR_PATCH_LOCATION_DATA_ADMIN_ERROR = "REQ_FOR_PATCH_LOCATION_DATA_ADMIN_ERROR"
// DELETE 
export const REQ_FOR_DELETE_LOCATION_DATA_ADMIN_PROGRESS = "REQ_FOR_DELETE_LOCATION_DATA_ADMIN_PROGRESS"
export const REQ_FOR_DELETE_LOCATION_DATA_ADMIN_SUCCESS = "REQ_FOR_DELETE_LOCATION_DATA_ADMIN_SUCCESS"
export const REQ_FOR_DELETE_LOCATION_DATA_ADMIN_ERROR = "REQ_FOR_DELETE_LOCATION_DATA_ADMIN_ERROR"


// =============================== ZONE =======================================

// GET 
export const REQ_FOR_GET_ZONE_PROGRESS = "REQ_FOR_GET_ZONE_PROGRESS"
export const REQ_FOR_GET_ZONE_SUCCESS = "REQ_FOR_GET_ZONE_SUCCESS"
export const REQ_FOR_GET_ZONE_ERROR = "REQ_FOR_GET_ZONE_ERROR"
// POST 
export const REQ_FOR_POST_ZONE_PROGRESS = "REQ_FOR_POST_ZONE_PROGRESS"
export const REQ_FOR_POST_ZONE_SUCCESS = "REQ_FOR_POST_ZONE_SUCCESS"
export const REQ_FOR_POST_ZONE_ERROR = "REQ_FOR_POST_ZONE_ERROR"
// PATCH 
export const REQ_FOR_PATCH_ZONE_PROGRESS = "REQ_FOR_PATCH_ZONE_PROGRESS"
export const REQ_FOR_PATCH_ZONE_SUCCESS = "REQ_FOR_PATCH_ZONE_SUCCESS"
export const REQ_FOR_PATCH_ZONE_ERROR = "REQ_FOR_PATCH_ZONE_ERROR"


// PATCH 
export const REQ_FOR_USER_CHANGE_ZONE_PROGRESS = "REQ_FOR_USER_CHANGE_ZONE_PROGRESS"
export const REQ_FOR_USER_CHANGE_ZONE_SUCCESS = "REQ_FOR_USER_CHANGE_ZONE_SUCCESS"
export const REQ_FOR_USER_CHANGE_ZONE_ERROR = "REQ_FOR_USER_CHANGE_ZONE_ERROR"


// =============================== USER =======================================


// POST 
export const REQ_FOR_POST_USER_PROGRESS = "REQ_FOR_POST_USER_PROGRESS"
export const REQ_FOR_POST_USER_SUCCESS = "REQ_FOR_POST_USER_SUCCESS"
export const REQ_FOR_POST_USER_ERROR = "REQ_FOR_POST_USER_ERROR"
// GET 
export const REQ_FOR_GET_USER_PROGRESS = "REQ_FOR_GET_USER_PROGRESS"
export const REQ_FOR_GET_USER_SUCCESS = "REQ_FOR_GET_USER_SUCCESS"
export const REQ_FOR_GET_USER_ERROR = "REQ_FOR_GET_USER_ERROR"
// GET - Each 
export const REQ_FOR_GET_EACH_USER_PROGRESS = "REQ_FOR_GET_EACH_USER_PROGRESS"
export const REQ_FOR_GET_EACH_USER_SUCCESS = "REQ_FOR_GET_EACH_USER_SUCCESS"
export const REQ_FOR_GET_EACH_USER_ERROR = "REQ_FOR_GET_EACH_USER_ERROR"
// PATCH - Each 
export const REQ_FOR_PATCH_EACH_USER_PROGRESS = "REQ_FOR_PATCH_EACH_USER_PROGRESS"
export const REQ_FOR_PATCH_EACH_USER_SUCCESS = "REQ_FOR_PATCH_EACH_USER_SUCCESS"
export const REQ_FOR_PATCH_EACH_USER_ERROR = "REQ_FOR_PATCH_EACH_USER_ERROR"

// PATCH - Active status 
export const REQ_FOR_PATCH_ACTIVE_STATUS_PROGRESS = "REQ_FOR_PATCH_ACTIVE_STATUS_PROGRESS"
export const REQ_FOR_PATCH_ACTIVE_STATUS_SUCCESS = "REQ_FOR_PATCH_ACTIVE_STATUS_SUCCESS"
export const REQ_FOR_PATCH_ACTIVE_STATUS_ERROR = "REQ_FOR_PATCH_ACTIVE_STATUS_ERROR"

// =============================== ROLE =======================================


// POST 
export const REQ_FOR_POST_ROLE_USER_PROGRESS = "REQ_FOR_POST_ROLE_USER_PROGRESS"
export const REQ_FOR_POST_ROLE_USER_SUCCESS = "REQ_FOR_POST_ROLE_USER_SUCCESS"
export const REQ_FOR_POST_ROLE_USER_ERROR = "REQ_FOR_POST_ROLE_USER_ERROR"

// =============================== REQUEST =======================================

export const REQ_FOR_GET_REQUEST_PROGRESS = "REQ_FOR_GET_REQUEST_PROGRESS"
export const REQ_FOR_GET_REQUEST_SUCCESS = "REQ_FOR_GET_REQUEST_SUCCESS"
export const REQ_FOR_GET_REQUEST_ERROR = "REQ_FOR_GET_REQUEST_ERROR"

export const REQ_FOR_PATCH_REQUEST_PROGRESS = "REQ_FOR_PATCH_REQUEST_PROGRESS"
export const REQ_FOR_PATCH_REQUEST_SUCCESS = "REQ_FOR_PATCH_REQUEST_SUCCESS"
export const REQ_FOR_PATCH_REQUEST_ERROR = "REQ_FOR_PATCH_REQUEST_ERROR"


// =============================== ATTENDANCE =======================================

// POST MASTER ATTENDANCE KEY
export const REQ_FOR_POST_MASTER_ATTENDANCE_KEY_PROGRESS = "REQ_FOR_POST_MASTER_ATTENDANCE_KEY_PROGRESS"
export const REQ_FOR_POST_MASTER_ATTENDANCE_KEY_SUCCESS = "REQ_FOR_POST_MASTER_ATTENDANCE_KEY_SUCCESS"
export const REQ_FOR_POST_MASTER_ATTENDANCE_KEY_ERROR = "REQ_FOR_POST_MASTER_ATTENDANCE_KEY_ERROR"

// POST MASTER ATTENDANCE SUBMIT
export const REQ_FOR_POST_MASTER_ATTENDANCE_SUBMIT_PROGRESS = "REQ_FOR_POST_MASTER_ATTENDANCE_SUBMIT_PROGRESS"
export const REQ_FOR_POST_MASTER_ATTENDANCE_SUBMIT_SUCCESS = "REQ_FOR_POST_MASTER_ATTENDANCE_SUBMIT_SUCCESS"
export const REQ_FOR_POST_MASTER_ATTENDANCE_SUBMIT_ERROR = "REQ_FOR_POST_MASTER_ATTENDANCE_SUBMIT_ERROR"

// POST 
export const REQ_FOR_POST_ATTENDANCE_PROGRESS = "REQ_FOR_POST_ATTENDANCE_PROGRESS"
export const REQ_FOR_POST_ATTENDANCE_SUCCESS = "REQ_FOR_POST_ATTENDANCE_SUCCESS"
export const REQ_FOR_POST_ATTENDANCE_ERROR = "REQ_FOR_POST_ATTENDANCE_ERROR"

// GET 
export const REQ_FOR_GET_ATTENDANCE_PROGRESS = "REQ_FOR_GET_ATTENDANCE_PROGRESS"
export const REQ_FOR_GET_ATTENDANCE_SUCCESS = "REQ_FOR_GET_ATTENDANCE_SUCCESS"
export const REQ_FOR_GET_ATTENDANCE_ERROR = "REQ_FOR_GET_ATTENDANCE_ERROR"

// PATCH 
export const REQ_FOR_PATCH_ATTENDANCE_PROGRESS = "REQ_FOR_PATCH_ATTENDANCE_PROGRESS"
export const REQ_FOR_PATCH_ATTENDANCE_SUCCESS = "REQ_FOR_PATCH_ATTENDANCE_SUCCESS"
export const REQ_FOR_PATCH_ATTENDANCE_ERROR = "REQ_FOR_PATCH_ATTENDANCE_ERROR"

// DELETE 
export const REQ_FOR_DELETE_ATTENDANCE_PROGRESS = "REQ_FOR_DELETE_ATTENDANCE_PROGRESS"
export const REQ_FOR_DELETE_ATTENDANCE_SUCCESS = "REQ_FOR_DELETE_ATTENDANCE_SUCCESS"
export const REQ_FOR_DELETE_ATTENDANCE_ERROR = "REQ_FOR_DELETE_ATTENDANCE_ERROR"
// GET_EACH 
export const REQ_FOR_GET_EACH_ATTENDANCE_PROGRESS = "REQ_FOR_GET_EACH_ATTENDANCE_PROGRESS"
export const REQ_FOR_GET_EACH_ATTENDANCE_SUCCESS = "REQ_FOR_GET_EACH_ATTENDANCE_SUCCESS"
export const REQ_FOR_GET_EACH_ATTENDANCE_ERROR = "REQ_FOR_GET_EACH_ATTENDANCE_ERROR"
// PATCH_EACH 
export const REQ_FOR_PATCH_EACH_ATTENDANCE_PROGRESS = "REQ_FOR_PATCH_EACH_ATTENDANCE_PROGRESS"
export const REQ_FOR_PATCH_EACH_ATTENDANCE_SUCCESS = "REQ_FOR_PATCH_EACH_ATTENDANCE_SUCCESS"
export const REQ_FOR_PATCH_EACH_ATTENDANCE_ERROR = "REQ_FOR_PATCH_EACH_ATTENDANCE_ERROR"
// GET_DETAILS Attendace
export const REQ_FOR_GET_DETAILS_ATTENDANCE_PROGRESS = "REQ_FOR_GET_DETAILS_ATTENDANCE_PROGRESS"
export const REQ_FOR_GET_DETAILS_ATTENDANCE_SUCCESS = "REQ_FOR_GET_DETAILS_ATTENDANCE_SUCCESS"
export const REQ_FOR_GET_DETAILS_ATTENDANCE_ERROR = "REQ_FOR_GET_DETAILS_ATTENDANCE_ERROR"

// GET_DETAILS_DATA Attendace (For callucation in attendance page)
export const REQ_FOR_GET_DETAILS_DATA_ATTENDANCE_PROGRESS = "REQ_FOR_GET_DETAILS_DATA_ATTENDANCE_PROGRESS"
export const REQ_FOR_GET_DETAILS_DATA_ATTENDANCE_SUCCESS = "REQ_FOR_GET_DETAILS_DATA_ATTENDANCE_SUCCESS"
export const REQ_FOR_GET_DETAILS_DATA_ATTENDANCE_ERROR = "REQ_FOR_GET_DETAILS_DATA_ATTENDANCE_ERROR"

// =============================== ATTENDANCE Access =======================================

// POST 
export const REQ_FOR_POST_ATTENDANCE_ACCESS_PROGRESS = "REQ_FOR_POST_ATTENDANCE_ACCESS_PROGRESS"
export const REQ_FOR_POST_ATTENDANCE_ACCESS_SUCCESS = "REQ_FOR_POST_ATTENDANCE_ACCESS_SUCCESS"
export const REQ_FOR_POST_ATTENDANCE_ACCESS_ERROR = "REQ_FOR_POST_ATTENDANCE_ACCESS_ERROR"



// =============================== SUBZONE =======================================

// GET 
export const REQ_FOR_GET_SUBZONE_PROGRESS = "REQ_FOR_GET_SUBZONE_PROGRESS"
export const REQ_FOR_GET_SUBZONE_SUCCESS = "REQ_FOR_GET_SUBZONE_SUCCESS"
export const REQ_FOR_GET_SUBZONE_ERROR = "REQ_FOR_GET_SUBZONE_ERROR"
// POST 
export const REQ_FOR_POST_SUBZONE_PROGRESS = "REQ_FOR_POST_SUBZONE_PROGRESS"
export const REQ_FOR_POST_SUBZONE_SUCCESS = "REQ_FOR_POST_SUBZONE_SUCCESS"
export const REQ_FOR_POST_SUBZONE_ERROR = "REQ_FOR_POST_SUBZONE_ERROR"
// PATCH 
export const REQ_FOR_PATCH_SUBZONE_PROGRESS = "REQ_FOR_PATCH_SUBZONE_PROGRESS"
export const REQ_FOR_PATCH_SUBZONE_SUCCESS = "REQ_FOR_PATCH_SUBZONE_SUCCESS"
export const REQ_FOR_PATCH_SUBZONE_ERROR = "REQ_FOR_PATCH_SUBZONE_ERROR"


// =============================== REMARK =======================================

// GET 
export const REQ_FOR_GET_REMARK_ADMIN_PROGRESS = "REQ_FOR_GET_REMARK_ADMIN_PROGRESS"
export const REQ_FOR_GET_REMARK_ADMIN_SUCCESS = "REQ_FOR_GET_REMARK_ADMIN_SUCCESS"
export const REQ_FOR_GET_REMARK_ADMIN_ERROR = "REQ_FOR_GET_REMARK_ADMIN_ERROR"
// POST 
export const REQ_FOR_POST_REMARK_ADMIN_PROGRESS = "REQ_FOR_POST_REMARK_ADMIN_PROGRESS"
export const REQ_FOR_POST_REMARK_ADMIN_SUCCESS = "REQ_FOR_POST_REMARK_ADMIN_SUCCESS"
export const REQ_FOR_POST_REMARK_ADMIN_ERROR = "REQ_FOR_POST_REMARK_ADMIN_ERROR"
// PATCH 
export const REQ_FOR_PATCH_REMARK_ADMIN_PROGRESS = "REQ_FOR_PATCH_REMARK_ADMIN_PROGRESS"
export const REQ_FOR_PATCH_REMARK_ADMIN_SUCCESS = "REQ_FOR_PATCH_REMARK_ADMIN_SUCCESS"
export const REQ_FOR_PATCH_REMARK_ADMIN_ERROR = "REQ_FOR_PATCH_REMARK_ADMIN_ERROR"
// DELETE 
export const REQ_FOR_DELETE_REMARK_ADMIN_PROGRESS = "REQ_FOR_DELETE_REMARK_ADMIN_PROGRESS"
export const REQ_FOR_DELETE_REMARK_ADMIN_SUCCESS = "REQ_FOR_DELETE_REMARK_ADMIN_SUCCESS"
export const REQ_FOR_DELETE_REMARK_ADMIN_ERROR = "REQ_FOR_DELETE_REMARK_ADMIN_ERROR"